[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit NeoPixel@^1.12.0
    ; For JSON parsing
    bblanchon/ArduinoJson@^7.0.0
    arduino-libraries/NTPClient@^3.2.1
    bblanchon/ArduinoJson@^6.21.4
    arduinoFFT
    knolleary/PubSubClient@2.8
    ncmreynolds/ld2410@^0.1.4
board_build.partitions = partitions.csv
build_flags = 
    -DARDUINO_ARCH_ESP32
    -DCONFIG_FREERTOS_UNICORE=1 
    -DCONFIG_DISABLE_HAL_LOCKS=1
