[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = 
    fastled/FastLED@^3.6.0
    ; For JSON parsing
    bblanchon/ArduinoJson@^7.0.0
    arduino-libraries/NTPClient@^3.2.1
    bblanchon/ArduinoJson@^6.21.4
    arduinoFFT
    knolleary/PubSubClient@2.8
    ncmreynolds/ld2410@^0.1.4
board_build.partitions = partitions.csv
build_flags = 
    #-D FASTLED_RMT_BUILTIN_DRIVER=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D HW_CDC=1

