[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi 
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.bootloader = qio 
lib_deps = 
    fastled/FastLED@^3.6.0
    arduino-libraries/NTPClient@^3.2.1
    arduinoFFT
    knolleary/PubSubClient@2.8
    ncmreynolds/ld2410@^0.1.4
    sinricpro/SinricPro@^3.3.0
    me-no-dev/AsyncTCP@^1.1.1
    adafruit/Adafruit INA219@^1.2.3
    adafruit/Adafruit VEML7700 Library @ 2.1.6
    me-no-dev/ESPAsyncTCP@^1.2.2
    https://github.com/me-no-dev/ESPAsyncWebServer.git
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
build_flags = 
    -DARDUINO_LOOP_STACK_SIZE=16384
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -D FASTLED_RMT_BUILTIN_DRIVER=1
    -DCONFIG_SPIRAM_USE_MALLOC=1
    -DCONFIG_ESP_COREDUMP_ENABLE_TO_FLASH=1
    -DCONFIG_ESP_COREDUMP_DATA_FORMAT_ELF=1
    -DCONFIG_ESP_COREDUMP_CHECKSUM_CRC32=1
    # Firebase optimizations
    -DFIREBASE_DISABLE_FIRESTORE
    -DFIREBASE_DISABLE_FCM
    -DFIREBASE_DISABLE_STORAGE
    -DFIREBASE_DISABLE_GCS
    -DFIREBASE_DISABLE_FUNCTIONS
[env:esp32-s3-debug]
extends = env:esp32-s3-devkitc-1
build_type = debug
monitor_filters = esp32_exception_decoder
build_flags = 
    ${env:esp32-s3-devkitc-1.build_flags}
    -DCORE_DEBUG_LEVEL=5